###
POST http://localhost:4000/api/v1/User/new_user
Content-Type: application/json

{
  "email": "user@mail.com",
  "firstName": "user",
  "lastName": "tester",
  "contact": "0974923302",
  "password": "12345678",   
  "address": "4 fir road, lusaka"
 
}

###
GET http://localhost:4000/api/v1/User/view_users

###
GET http://localhost:4000/api/v1/User/view_user/626fe0d9a2bcc82f906e7979

