###
POST http://localhost:5000/api/v1/Order/new_inventory
Content-Type: application/json

{

}

###
GET http://localhost:5000/api/v1/Order/get_inventorys

###
GET http://localhost:5000/api/v1/Order/get_inventory/626fa8b4654a84dc7694eb81